#https://tomverbeure.github.io/2019/08/03/Video-Timings-Calculator.html
Section "Device"
    Identifier  "DummyDevice"
    Driver      "dummy"
    VideoRam    4096
EndSection

Section "Monitor"
    Identifier   "DummyMonitor"
    HorizSync    10.0-20.0
    VertRefresh  15.0-25.0
    Modeline     "1360x768" 26.25 1360 1400 1528 1696 768 771 781 787
EndSection

Section "Screen"
    Identifier    "WXGA"
    Device        "DummyDevice"
    Monitor       "DummyMonitor"
    DefaultDepth  16
    SubSection "Display"
        Depth  16
        Modes  "1360x768"
    EndSubSection
EndSection
